name: 'velib_project'
version: '1.0.0'
config-version: 2

profile: 'velib_project'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  velib_project:

    bronze:
      +schema: bronze
      +materialized: view   # tu n’auras sûrement pas de modèles bronze, mais OK

    staging:
      +schema: silver
      +materialized: incremental   # par défaut, tout le layer staging est incrémental
      +incremental_strategy: delete+insert
      +unique_key: file_name       # peut être override dans les modèles

    marts:
      +schema: gold
      +materialized: table
