USE DATABASE VELIB_DB;
USE SCHEMA GOLD;

CREATE OR REPLACE TABLE DIM_DATE AS
WITH dates AS (
    SELECT
        SEQ4() AS seq
    FROM TABLE(GENERATOR(ROWCOUNT => 3650)) -- environ 10 ans
)
SELECT
    TO_DATE('2020-01-01') + seq AS date,
    TO_NUMBER(TO_CHAR(TO_DATE('2020-01-01') + seq, 'YYYYMMDD')) AS date_key,
    EXTRACT(YEAR FROM TO_DATE('2020-01-01') + seq) AS year,
    EXTRACT(MONTH FROM TO_DATE('2020-01-01') + seq) AS month,
    EXTRACT(DAY FROM TO_DATE('2020-01-01') + seq) AS day,
    EXTRACT(DAYOFWEEK FROM TO_DATE('2020-01-01') + seq) AS weekday,
    WEEKOFYEAR(TO_DATE('2020-01-01') + seq) AS weeknum,
    CASE WHEN EXTRACT(DAYOFWEEK FROM TO_DATE('2020-01-01') + seq) IN (1,7) THEN TRUE ELSE FALSE END AS is_weekend
FROM dates;