USE DATABASE VELIB_DB;
USE SCHEMA BRONZE;  
DESC INTEGRATION GCS_VELIB_INTEGRATION_V2;

CREATE STAGE STAGE_STATION_DETAILS 
	URL = 'gcs://bucket-velib/station_details/' 
	STORAGE_INTEGRATION = GCS_VELIB_INTEGRATION_V2 
	DIRECTORY = ( ENABLE = true AUTO_REFRESH = true NOTIFICATION_INTEGRATION = 'GCS_INT' );